name: CovingtonDoan
favicon: null
layout_spectrum: 0.7433374442625791
typography_spectrum: 0.6056966120377183
title: Covington Doan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7836294113658369
  lightness: 0.9995844296645373
  saturation: 0.6614427228923887
  rhythmicContrast: 0.6077655982226133
purpose: []
